name: CI - TDD y BDD

on:
  push:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave pytest pytest-cov flake8

      - name: Ejecutar Pytest con cobertura
        run: |
          pytest --cov=src tests/ > pytest-report.txt

      - name: Ejecutar Behave
        run: |
          behave > behave-report.txt

      - name: Verificar estilo con flake8
        run: |
          flake8 src tests features

      - name: Subir reportes como artifacts
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            pytest-report.txt
            behave-report.txt

      - name: Analizar con SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: JesusOsorio-19_CC3S2-251
          SONAR_ORGANIZATION: jesusosorio-19
