name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave pytest pytest-cov
        pip install -e .

    - name: Run unit tests with pytest
      run: |
        pytest tests/ --cov=src --cov-report=xml --junitxml=test-results/junit.xml -v

    - name: Run BDD tests with behave
      run: |
        behave --format junit --outfile test-results/behave-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/

    - name: Upload coverage report
      uses: codecov/codecov-action@v3