name: CI - TDD y BDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install behave pytest flake8 pytest-cov

    - name: Ejecutar Pytest con cobertura
      run: |
        pytest --cov=src tests/ > pytest-report.txt

    - name: Ejecutar Behave
      run: |
        behave > behave-report.txt

    - name: Verificar estilo con flake8
      run: |
        flake8 src tests features

    - name: Subir reportes como artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          pytest-report.txt
          behave-report.txt

