name: CI - TDD y BDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r Actividades/Actividad7/belly_project/requirements.txt

    - name: Ejecutar Pytest
      run: |
        pytest --cov=src tests/

    - name: Ejecutar Behave
      run: |
        behave

    - name: Verificar con flake8
      run: |
        flake8 src tests features

    - name: Análisis SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
