name: CI - BDD y TDD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Actividades/Actividad7/belly_project

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest behave pytest-cov pytest-html

      - name: Ejecutar Pytest con cobertura y reporte HTML
        run: pytest --cov=src tests/ --html=pytest-report.html

      - name: Ejecutar Behave con reporte JUnit
        run: behave --junit --junit-directory=reportes/

      - name: Subir reportes como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reportes-de-pruebas
          path: |
            Actividades/Actividad7/belly_project/pytest-report.html
            Actividades/Actividad7/belly_project/reportes/
