name: CI - BDD y TDD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Actividades/Actividad7/belly_project

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest behave pytest-cov flake8

      - name: Ejecutar Pytest con cobertura
        run: pytest --cov=src tests/ > pytest-report.txt

      - name: Ejecutar Behave
        run: behave > behave-report.txt

      - name: Verificar estilo con flake8
        run: flake8 src tests features

      - name: Subir reportes como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reportes-de-pruebas
          path: |
            pytest-report.txt
            behave-report.txt
